apiVersion: v1
kind: Pod
metadata:
  name: poi
  namespace: insurance-api
  labels:
    app: poi
    aadpodidbinding: "vault-identity"
spec:
  volumes:
  - name: secrets-store-poi
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-kvname-podid"
  containers:
  - name: poi
    image: registrykua3387.azurecr.io/poi
    volumeMounts:
    - name: secrets-store-poi
      mountPath: "/mnt/secrets"
      readOnly: true
    ports:
    - containerPort: 80
    env:
      - name: SQL_SERVER
        value: "sqlserverkua3387.database.windows.net"
      - name: SQL_DBNAME
        value: "mydrivingDB"
      - name: ASPNETCORE_ENVIRONMENT
        value: "Local"
      - name: CONFIG_FILES_PATH
        value: "/mnt/secrets"
  nodeSelector:
    kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: insurance-api
spec:  
  selector:
    app: poi
  ports:
  - protocol: TCP
    port: 80    
  type: ClusterIP