apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: insurance-api
  labels:
    app: userprofile
    aadpodidbinding: "vault-identity"
spec:
  selector: 
    matchLabels: 
      app: userprofile
  template:
    metadata:
      labels: 
        app: userprofile
        aadpodidbinding: "vault-identity"
    spec:
      volumes:
      - name: secrets-store-userprofile
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-podid"
      containers:
      - name: userprofile
        image: registrykua3387.azurecr.io/userprofile
        volumeMounts:
        - name: secrets-store-userprofile
          mountPath: "/mnt/secrets"
          readOnly: true
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:        
        - name: SQL_SERVER
          value: "sqlserverkua3387.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: CONFIG_FILES_PATH
          value: "/mnt/secrets"
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: insurance-api
spec:
  selector:
    app: userprofile
  ports:
  - protocol: TCP
    port: 80
  type: ClusterIP
