apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: azure-identity
spec:
  type: 0
  resourceID: /subscriptions/34c68fe3-f615-4eb7-8925-4599d11b0aa6/resourceGroups/teamResources/providers/Microsoft.ManagedIdentity/userAssignedIdentities/vault-identity
  clientID: "f2f5ebe3-80ef-44a9-a1d6-b2a7864c01e2"
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: azure-identity-binding
spec:
  azureIdentity: "azure-identity"
  selector: "vault-identity"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-podid
  namespace: insurance-api
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"               # Set to true for using aad-pod-identity to access keyvault
    keyvaultName: "KeyVaultTeam6"        # Set to the name of your Azure Key Vault instance
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQL-USER
          objectType: secret             # object types: secret, key or cert
        - |
          objectName: SQL-PASSWORD
          objectType: secret             # object types: secret, key or cert
    tenantId: "bcc7953f-b0a7-4566-8c7f-8fa3840a3012"                # The tenant ID of the Azure Key Vault instance