apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: insurance-api
  labels:
    app: user-java
    aadpodidbinding: "vault-identity"
spec:
  selector: 
    matchLabels: 
      app: user-java
  template:
    metadata:
      labels: 
        app: user-java
        aadpodidbinding: "vault-identity"
    spec:
      volumes:
      - name: secrets-store-user-java
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-podid"
      containers:
      - name: user-java
        image: registrykua3387.azurecr.io/user-java
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: secrets-store-user-java
          mountPath: "/secrets"
          readOnly: true
        ports:
        - containerPort: 80
        env:        
        - name: SQL_SERVER
          value: "sqlserverkua3387.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"        
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: insurance-api
spec:  
  selector:
    app: user-java
  ports:
  - protocol: TCP
    port: 80
  type: ClusterIP
