apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: insurance-api 
  labels:
    app: trips
    aadpodidbinding: "vault-identity"
spec:
  selector: 
    matchLabels: 
      app: trips
  template:
    metadata:
      labels: 
        app: trips
        aadpodidbinding: "vault-identity"
    spec:
      volumes:
      - name: secrets-store-trips
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-podid"
      containers:
      - name: trips
        image: registrykua3387.azurecr.io/trips
        volumeMounts:
        - name: secrets-store-trips
          mountPath: "/mnt/secrets"
          readOnly: true
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: SQL_SERVER
          value: "sqlserverkua3387.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: CONFIG_FILES_PATH
          value: "/mnt/secrets"
      nodeSelector:
        kubernetes.io/os: linux

---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: insurance-api
spec:  
  selector:
    app: trips
  ports:
  - protocol: TCP
    port: 80
  type: ClusterIP
